### ISSUE TITLE
Issues + fixes

### ISSUE THREAD

**Issue by JankyProgrammer** [KrisKamweru/bbs-auto-bot#4]
[1] When I was initially trying to get the program to operate I kept getting held up at the prepare for quest stage.
[2] Cancel Ally is outdated therefore this will not work.
[3] Basically all the jpgs assets didn't work for me perhaps it's best to change them to png's
[4] Sometimes if starting on stage which is on the far right the program will fail for example of stage 12.

Issue in detail: 
[1] After doing some debugging (I guess you could call it that), I basically found out that the tryFindAndClick function was not picking up prep_for_quest.jpg for whatever reason (guessing because the monitor I have (1440p not 1080).
[2] Cancel Ally now requires the user to switch to another tab.

Fixes: 
[1] Basically made my own asset using the snipping tool and saved it over the previous image in the assets folder to fix this.
[2] Create an an asset of the Allies tab then type findAndClickWhenFound("assets\[filename.jpg]") one line above findAndClickWhenFound("assets\cancel_ally.jpg")

example: 
![get_ally_tab](https://user-images.githubusercontent.com/83861336/117533229-98bea500-afe3-11eb-973b-bf3c1e61310a.JPG)

[3] Make your own assets lol
[4] Idk i'll look into it.

FINAL NOTES:

The program won't work with steam since the steam client is too big and unsizable therefore its suggested to use bluestacks however the author has already kinda stated this.

I'm considering making a GUI for this , if it gets any attention what so ever (basically if ppl want it).

If the author decides to come back to bbs, I wouldn't mind helping make additional functionality such as sub quests.

If for whatever reason the modules don't install here is a list of the required modules.
So you can install them manually: 

pip3 install pyautogui or pip install pyautogui
pip install pywin32 (for win32/wincon)
pip3 install keyboard

**Comment by KrisKamweru** [comment]
> [1] When I was initially trying to get the program to operate I kept getting held up at the prepare for quest stage.
> [2] Cancel Ally is outdated therefore this will not work.
> [3] Basically all the jpgs assets didn't work for me perhaps it's best to change them to png's
> [4] Sometimes if starting on stage which is on the far right the program will fail for example of stage 12.
> 
> Issue in detail:
> [1] After doing some debugging (I guess you could call it that), I basically found out that the tryFindAndClick function was not picking up prep_for_quest.jpg for whatever reason (guessing because the monitor I have (1440p not 1080).
> [2] Cancel Ally now requires the user to switch to another tab.
> 
> Fixes:
> [1] Basically made my own asset using the snipping tool and saved it over the previous image in the assets folder to fix this.
> [2] Create an an asset of the Allies tab then type findAndClickWhenFound("assets[filename.jpg]") one line above findAndClickWhenFound("assets\cancel_ally.jpg")
> 
> example:
> ![get_ally_tab](https://user-images.githubusercontent.com/83861336/117533229-98bea500-afe3-11eb-973b-bf3c1e61310a.JPG)
> 
> [3] Make your own assets lol
> [4] Idk i'll look into it.
> 
> FINAL NOTES:
> 
> The program won't work with steam since the steam client is too big and unsizable therefore its suggested to use bluestacks however the author has already kinda stated this.
> 
> I'm considering making a GUI for this , if it gets any attention what so ever (basically if ppl want it).
> 
> If the author decides to come back to bbs, I wouldn't mind helping make additional functionality such as sub quests.
> 
> If for whatever reason the modules don't install here is a list of the required modules.
> So you can install them manually:
> 
> pip3 install pyautogui or pip install pyautogui
> pip install pywin32 (for win32/wincon)
> pip3 install keyboard

First off, thanks for looking into this. I really appreciate it
Seems you had a good handle on fixing issue 1-3 so kudos, not much for me to add there really.

For issue 4, could be an issue with either the asset itself looking different and thus not being picked up by the bot or tryFindLeftMostAndClick() acting up. Might be a good place to start. 

I'm currently on a bbs hiatus so I can't look into them soon, but I figured that's as good a place as any to start looking. You can fork if you want, or I can add you as a collaborator as well. I don't mind either option

**Comment by sick107** [comment]
Hey, any news on this yet?
