### ISSUE TITLE
pyautogui

### ISSUE THREAD

**Issue by TTVswixelz** [KrisKamweru/bbs-auto-bot#5]
whenever I try to run the bot it says this.
Traceback (most recent call last):
  File "farmbot.py", line 59, in <module>
    from pyautogui import *
ModuleNotFoundError: No module named 'pyautogui'

**Comment by TTVswixelz** [comment]
i fixed that part now when I run it It just stays frozen and no commands come up and nothing is happening to the bleach brave souls.

**Comment by Zhalo2** [comment]
How did you fix the pyeautogui issue ? Thanks
