### ISSUE TITLE
Unable to run the bot

### ISSUE THREAD

**Issue by 0reste7** [KrisKamweru/bbs-auto-bot#6]
![Screenshot (44)](https://user-images.githubusercontent.com/89419311/130510254-27d23a16-f59e-425e-9f61-f4e589295601.png)
![Screenshot (45)](https://user-images.githubusercontent.com/89419311/130510369-f7c29e44-70ac-422d-9fda-6af361543da0.png)
I'm getting those two errors and i have no idea of what they are. Can someone help me out?

**Comment by sick107** [comment]
I bypassed this by downgrading to python 3.9.0, and installing opencv via pip with that version.

**Comment by KrisKamweru** [comment]
As @sick107 said, probably old versions of python and the library causing issues. Bot is pretty unusable right now as is anyways. Would need some work to bring it up to date both in terms of the logic it uses and the code versions
