### ISSUE TITLE
Issue with the execution of the script 

### ISSUE THREAD

**Issue by Solo34080** [KrisKamweru/bbs-auto-bot#8]
i have the  " OSError : screen grab failed" error , can you please help me it'd be very cool

**Comment by KrisKamweru** [comment]
The code is probably horribly out of date in many ways at this point. I'd have to go over it again and see wassup. Can't say if or when though

I did see someone fork it though. Maybe check their version?
Lemme see if I can find it

**Comment by KrisKamweru** [comment]
Found it
Maybe check [this version](https://github.com/KaZMo7/bbs-auto-bot)
